### ISSUE TITLE
offer support for `next-ls` and `lexical`

### ISSUE THREAD

**Issue by NobbZ** [shanesveller/nix-beam-overlay#35]
Please provide support for the 2 alternative language servers.

This could be done by providing explicit options and packages for them, or by just accepting a `languageServerPackage` or similar.

**Comment by shanesveller** [comment]
I'm generally in favor of including this 👍🏻, but it may take me a little bit to implement and I don't have an ETA. In the meantime, if there is anywhere in the current Nix code where I've embedded any assumptions that actively prevent use of those LSPs instead, I would very likely consider that a bug and would welcome additional reports about such. 

I will possibly have to tackle this the way you suggested, a package argument plus deliberate documentation, since we don't have optional dependencies in flakes yet and I don't want to require that all consumers depend on an additional input for these.

For example if someone wanted to bundle `next-ls` today, I believe they could use Mitchell's flake directly from the project's own repository as a flake input, and put its `inputs.next-ls.packages.${system}.default` into my flake modules' option, `perSystem.beamWorkspace.devShell.extraPackages`, and any envvars into `perSystem.beamWorkspace.devShell.extraArgs`. Then you just need to configure your $EDITOR accordingly to activate it it, and make sure to set or leave the default of `perSystem.beamWorkspace.devShell.languageServers.elixir = false;` to omit `elixir-ls`.

Aside: I haven't really experimented with either alternative LSP for personal use yet, so I would be interested in chatting about anecdotes from other users. If you or anyone reading would like to share notes, please feel free to reach out me on the Discord that's linked from the language homepage, or on ElixirForum. My username should match what I have here in both cases. 🍻

**Comment by NobbZ** [comment]
I have not yet experimented with them either, though indeed I wanted to get both into nixpkgs over the next couple of days.

That would make it easier for you to just provide them as is.

Currently replacing the elixir-ls with a "master" or nightly build is already non-obvious.

**Comment by shanesveller** [comment]
Hi, sorry, please see #53 for slightly more detail but I no longer expect to work on this myself.
