### ISSUE TITLE
How to use "ref:main" for Elixir version?

### ISSUE THREAD

**Issue by mhanberg** [shanesveller/nix-beam-overlay#43]
Thanks for this flake setup!

I am needing to only test a project against the Elixir main branch (and update it frequently), and I'm not entirely sure how to do that with this nix package.

Is it possible?

Thanks!

**Comment by shanesveller** [comment]
Hey @mhanberg , thanks for this question! Today, this is a fairly unpleasant experience - some past assumptions also prevented me from trivially supporting RCs as well, and this question is basically a superset of that.

In case it helps unblock you, I've got a diff against `./dev/example/flake.nix` that demonstrates how this is possible in the flake-lib as it exists today.

Obviously the ergonomics here leave **much** to be desired, so I'll be mulling over when and where to make adjustments to make it more readily possible to inject the `rev`/`sha256` arguments needed to use an arbitrarily-chosen commit.

https://github.com/shanesveller/nix-beam-flakes/compare/shanesveller/elixir-main-demo?expand=1

https://github.com/shanesveller/nix-beam-flakes/blob/724c72e2aa69466eff4468c4593fa492c8481778/dev/example/flake.nix#L31-L70

**Comment by shanesveller** [comment]
> (and update it frequently)

I kind of glossed over this in the first reply - I've had pretty good luck with tools like https://github.com/berberman/nvfetcher for that. It's a little high-ceremony but if you're only following the one, that's not too bad. I tried using it for Neovim plugins for a little while and that was too much toil for my taste.

Your vanilla option instead is `nix-prefetch-git` to get the checksum, or lean into the TOFU technique I mentioned in a code comment.

You could also commit Flake Crimes and add the Elixir repo itself to your inputs with something like:
```nix
inputs.elixir.url = "github:elixir-lang/elixir";
inputs.elixir.flake = false;
```

And then where you give `rev`/`sha256`, drop those and do `src = inputs.elixir.outPath` and see how far you get. I think it would likely work, possibly with mild tweaks since I'm writing from memory. This moves the update mechanism to `nix flake lock --update-input elixir --commit-lock-file`.

I generally discourage putting non-Nix repos as a flake input as it's not really the intended use, it's sort of like trying to install an NPM package with Rubygems, and it's a good way to get yourself a temporary rate limit on GitHub's end if you abuse it too much.

**Comment by mhanberg** [comment]
Thanks! I'll close this for now.
